name: Test GIT Actions workflow

on:
  schedule:
    # This example runs every day at 2:30 AM UTC
    - cron: '35 6 * * 1-5'
    
  workflow_dispatch:  # To manually trigger the workflow if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Adjust this as needed
          distribution: 'temurin'  # Use Temurin, the supported distribution
          
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get -y --fix-broken install

      - name: Install ChromeDriver (for Chrome version 131)
        run: |
          wget https://storage.googleapis.com/chrome-for-testing-public/134.0.6998.88/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
      - name: Run mvn test
        run: mvn test
